name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Retrieve version
        run: |
          echo VERSION=`awk -F "=" '$1 == "appVerName" {print $2}' gradle.properties` >> $GITHUB_ENV
      - name: Cache gradle dep
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            !~/.gradle/caches/build-cache-*
          key: gradle-deps-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-deps
      - name: Install dep
        run: |
          sudo apt-get install -y ccache ninja-build
          ccache -o max_size=1G
          ccache -o hash_dir=false
          ccache -o compiler_check='%compiler% -dumpmachine; %compiler% -dumpversion'
          ccache -zp
      - name: Cache gradle build
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/build-cache-*
          key: gradle-builds-${{ github.sha }}
          restore-keys: gradle-builds
      - name: Cache native build
        uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
          key: native-cache-${{ github.sha }}
          restore-keys: native-cache-
      - name: Build with Gradle
        run: |
          echo 'org.gradle.caching=true' >> gradle.properties
          echo 'org.gradle.parallel=true' >> gradle.properties
          echo 'org.gradle.vfs.watch=true' >> gradle.properties
          echo 'org.gradle.jvmargs=-Xmx2048m' >> gradle.properties
          echo 'android.native.buildOutput=verbose' >> gradle.properties
          ln -s $(which ninja) $(dirname $(which cmake)) # https://issuetracker.google.com/issues/206099937
          echo "cmake.dir=$(dirname $(dirname $(which cmake)))" >> local.properties
          ./gradlew -PappVerName=${{ env.VERSION }} assembleRelease assembleDebug
          ccache -s
      - name: Sign Android release
        if: success()
        id: sign
        uses: r0adkll/sign-android-release@v1.0.4
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
        with:
          releaseDirectory: app/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
              ${{ steps.sign.outputs.signedReleaseFile }}

      - name: Post to channel
        if: startsWith(github.ref, 'refs/tags/')
        env:
          CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          FILE: ${{ steps.sign.outputs.signedReleaseFile }}
          COMMIT_MESSAGE: |+
            \#哔哩漫游 \#Plus
            哔哩漫游Plus正式版
            ●增加番剧字幕繁转简\&魔法刻录\&更多功能
            ▲不支持 太极\/应用转生\/EdXposed
        run: |
          ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
          curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22parse_mode%22:%22MarkdownV2%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
