name: Sync Fork

on:
  schedule:
    - cron: '1 0-14 * * *'
  workflow_dispatch:

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest

    steps:
      - name: Get repo name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Sync fork
        id: sync
        uses: zjns/repo-sync@master
        with:
          token: ${{ secrets.HUB_TOKEN }}
          up_repo: 'yujincheng08/BiliRoaming'
          up_branch: master
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
